version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    #image: prismagraphql/mongo-single-replica:4.4.3-bionic
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network


  mongo-express:
      image: mongo-express
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb_container
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: prisma
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: pass
      ports:
        - "8081:8081"
      depends_on:
        - mongodb_container
      networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge
